# Generated by Django 4.0.4 on 2022-05-14 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('tmvdbid', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mo_img', models.CharField(max_length=500)),
                ('mo_link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Movie Management',
                'verbose_name_plural': 'Movie Management',
                'ordering': ['add_date'],
            },
        ),
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent_state', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.client')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movies')),
            ],
            options={
                'ordering': ['re_add_date'],
            },
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField()),
                ('recharge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recharge_state', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.client')),
            ],
            options={
                'verbose_name': 'Recharge Management',
                'verbose_name_plural': 'Recharge Management',
                'ordering': ['recharge_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.client')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movies')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_movie_id', models.IntegerField()),
                ('w_title', models.CharField(max_length=100)),
                ('w_vote_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('w_img', models.CharField(max_length=500)),
                ('w_add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.client')),
            ],
            options={
                'unique_together': {('client', 'w_movie_id')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('request_state', models.CharField(choices=[('Requested', 'Requested'), ('Purchase Order', 'Purchase Order'), ('Available', 'Available')], default='Requested', max_length=20)),
                ('rq_title', models.CharField(max_length=100)),
                ('rq_vote_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rq_img', models.CharField(max_length=500)),
                ('rq_add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.client')),
            ],
            options={
                'verbose_name': 'Request Management',
                'verbose_name_plural': 'Request Management',
                'ordering': ['rq_add_date'],
                'unique_together': {('client', 'movie_id')},
            },
        ),
    ]
